#This page contains Numbered Patterns:

# for row in range(1,6):
#     for col in range(1,row+1):
#         print(row, end="")
#     print()


for row in range(1,6):
    for col in range(1,row+1):
        print(col, end="")
    print()


# for row in range(1,6) :
#     for col in range(1,7-row) :
#         print(col, end="")
#     print()


# for row in range(1,6) :
#     for col in range(5, row-1, -1) :
#         print(col, end="")
#     print()