name = input("Enter your name: ")
Age = int(input("Enter your age: "))
Fav_number = int(input("Enter your favorite number: "))

print(f"My name is {name}.")
print(f"My age is {Age} years.")
print(f"My favorite number is {Fav_number}.")

Fav_number_sqaured = Fav_number**2
print(f"Favorite number sqaured {Fav_number_sqaured}.")
Fav_number_cubed = Fav_number**3
print(f"Favorite number cubed {Fav_number_cubed}.")

Age = float(Age)
print(type(Age))
Age = str(Age)
print(type(Age))

is_student = True
has_laptop = False
print(is_student)
print(has_laptop)
print(type(is_student))
print(type(has_laptop))
